# Generated by Django 3.1.3 on 2020-11-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equation', models.CharField(max_length=30, verbose_name='Формула функции')),
                ('graph', models.ImageField(blank=True, null=True, upload_to='', verbose_name='График функции')),
                ('datetime', models.DateTimeField(verbose_name='Дата обработки')),
                ('interval', models.IntegerField(verbose_name='Глубина периода моделирования в днях')),
                ('dt', models.IntegerField(verbose_name='Шаг в часах')),
                ('exception', models.CharField(max_length=50, verbose_name='Формула функции')),
            ],
        ),
    ]
