# Generated by Django 3.1.3 on 2020-11-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='exception',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ошибка'),
        ),
    ]
