# Generated by Django 3.1.3 on 2020-11-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0002_auto_20201121_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки'),
        ),
    ]
